from setuptools import setup

setup(
    name='tarder-sync',
    version='0.1',
    packages=['venv.Lib.site-packages.pip', 'venv.Lib.site-packages.pip._vendor',
              'venv.Lib.site-packages.pip._vendor.idna', 'venv.Lib.site-packages.pip._vendor.pep517',
              'venv.Lib.site-packages.pip._vendor.pytoml', 'venv.Lib.site-packages.pip._vendor.certifi',
              'venv.Lib.site-packages.pip._vendor.chardet', 'venv.Lib.site-packages.pip._vendor.chardet.cli',
              'venv.Lib.site-packages.pip._vendor.distlib', 'venv.Lib.site-packages.pip._vendor.distlib._backport',
              'venv.Lib.site-packages.pip._vendor.msgpack', 'venv.Lib.site-packages.pip._vendor.urllib3',
              'venv.Lib.site-packages.pip._vendor.urllib3.util', 'venv.Lib.site-packages.pip._vendor.urllib3.contrib',
              'venv.Lib.site-packages.pip._vendor.urllib3.contrib._securetransport',
              'venv.Lib.site-packages.pip._vendor.urllib3.packages',
              'venv.Lib.site-packages.pip._vendor.urllib3.packages.backports',
              'venv.Lib.site-packages.pip._vendor.urllib3.packages.ssl_match_hostname',
              'venv.Lib.site-packages.pip._vendor.colorama', 'venv.Lib.site-packages.pip._vendor.html5lib',
              'venv.Lib.site-packages.pip._vendor.html5lib._trie',
              'venv.Lib.site-packages.pip._vendor.html5lib.filters',
              'venv.Lib.site-packages.pip._vendor.html5lib.treewalkers',
              'venv.Lib.site-packages.pip._vendor.html5lib.treeadapters',
              'venv.Lib.site-packages.pip._vendor.html5lib.treebuilders', 'venv.Lib.site-packages.pip._vendor.progress',
              'venv.Lib.site-packages.pip._vendor.requests', 'venv.Lib.site-packages.pip._vendor.packaging',
              'venv.Lib.site-packages.pip._vendor.cachecontrol',
              'venv.Lib.site-packages.pip._vendor.cachecontrol.caches',
              'venv.Lib.site-packages.pip._vendor.webencodings', 'venv.Lib.site-packages.pip._vendor.pkg_resources',
              'venv.Lib.site-packages.pip._internal', 'venv.Lib.site-packages.pip._internal.cli',
              'venv.Lib.site-packages.pip._internal.req', 'venv.Lib.site-packages.pip._internal.vcs',
              'venv.Lib.site-packages.pip._internal.index', 'venv.Lib.site-packages.pip._internal.utils',
              'venv.Lib.site-packages.pip._internal.models', 'venv.Lib.site-packages.pip._internal.network',
              'venv.Lib.site-packages.pip._internal.commands', 'venv.Lib.site-packages.pip._internal.operations',
              'venv.Lib.site-packages.pip._internal.operations.build',
              'venv.Lib.site-packages.pip._internal.operations.install',
              'venv.Lib.site-packages.pip._internal.distributions', 'venv.Lib.site-packages.isapi',
              'venv.Lib.site-packages.wheel', 'venv.Lib.site-packages.wheel.cli', 'venv.Lib.site-packages.PySide2',
              'venv.Lib.site-packages.PySide2.scripts', 'venv.Lib.site-packages.PySide2.support',
              'venv.Lib.site-packages.adodbapi', 'venv.Lib.site-packages.colorama', 'venv.Lib.site-packages.colorlog',
              'venv.Lib.site-packages.win32com', 'venv.Lib.site-packages.win32com.test',
              'venv.Lib.site-packages.win32com.demos', 'venv.Lib.site-packages.win32com.client',
              'venv.Lib.site-packages.win32com.makegw', 'venv.Lib.site-packages.win32com.server',
              'venv.Lib.site-packages.win32com.servers', 'venv.Lib.site-packages.pythonwin.pywin',
              'venv.Lib.site-packages.pythonwin.pywin.mfc', 'venv.Lib.site-packages.pythonwin.pywin.idle',
              'venv.Lib.site-packages.pythonwin.pywin.Demos.ocx', 'venv.Lib.site-packages.pythonwin.pywin.tools',
              'venv.Lib.site-packages.pythonwin.pywin.dialogs', 'venv.Lib.site-packages.pythonwin.pywin.docking',
              'venv.Lib.site-packages.pythonwin.pywin.debugger', 'venv.Lib.site-packages.pythonwin.pywin.framework',
              'venv.Lib.site-packages.pythonwin.pywin.framework.editor',
              'venv.Lib.site-packages.pythonwin.pywin.framework.editor.color',
              'venv.Lib.site-packages.pythonwin.pywin.scintilla', 'venv.Lib.site-packages.shiboken2',
              'venv.Lib.site-packages.shiboken2.files.dir.shibokensupport',
              'venv.Lib.site-packages.shiboken2.files.dir.shibokensupport.signature',
              'venv.Lib.site-packages.shiboken2.files.dir.shibokensupport.signature.lib',
              'venv.Lib.site-packages.setuptools', 'venv.Lib.site-packages.setuptools.extern',
              'venv.Lib.site-packages.setuptools._vendor', 'venv.Lib.site-packages.setuptools._vendor.packaging',
              'venv.Lib.site-packages.setuptools.command', 'venv.Lib.site-packages.win32comext.adsi',
              'venv.Lib.site-packages.win32comext.bits', 'venv.Lib.site-packages.win32comext.mapi',
              'venv.Lib.site-packages.win32comext.shell', 'venv.Lib.site-packages.win32comext.axdebug',
              'venv.Lib.site-packages.win32comext.ifilter', 'venv.Lib.site-packages.win32comext.propsys',
              'venv.Lib.site-packages.win32comext.axscript', 'venv.Lib.site-packages.win32comext.axscript.client',
              'venv.Lib.site-packages.win32comext.axscript.server', 'venv.Lib.site-packages.win32comext.internet',
              'venv.Lib.site-packages.win32comext.axcontrol', 'venv.Lib.site-packages.win32comext.directsound',
              'venv.Lib.site-packages.win32comext.directsound.test', 'venv.Lib.site-packages.win32comext.authorization',
              'venv.Lib.site-packages.win32comext.taskscheduler', 'venv.Lib.site-packages.pkg_resources',
              'venv.Lib.site-packages.pkg_resources.extern', 'venv.Lib.site-packages.pkg_resources._vendor',
              'venv.Lib.site-packages.pkg_resources._vendor.packaging'],
    url='http://tarder.ru',
    license='MIT',
    author='tarder',
    author_email='info@tarder.ru',
    description=''
)
