

class Constants:
    APP_VERSION = '0.0.4'

    PERIOD_COMPANIES = 60 * 60
    PERIOD_COMPANIES_ERROR = 5 * 60
    PERIOD_ITEMS = 15 * 60
    PERIOD_ITEMS_ERROR = 5 * 60

    LOG_GOOD = 50

    COMPANY_TAB_LOG = 0
    COMPANY_TAB_ITEMS = 1
    COMPANY_TAB_POINTS = 2
    COMPANY_TAB_ITEM_IN_POINTS = 3


    CONNECTION_TYPE_1C_FILE = 0
    CONNECTION_TYPE_1C_SERVER = 1

    TYPE_1C_AUTO = 0
    TYPE_1C_RETAIL = 1
    TYPE_1C_TRADE = 2
    TYPE_1C_BUH = 3

    COLOR_RED = '#b90101'
    COLOR_RED_LIGHT = '#bd3a26'
    COLOR_GREEN = '#057b00'
    COLOR_BLACK = '#000'
    COLOR_GREY = 'grey'